# ==========================================
# CINEPASS EUREKA SERVER
# ==========================================

# Application name
spring.application.name=eureka-server

# Eureka Server port
server.port=8761

# ------------------------------------------
# Eureka Server Configuration
# ------------------------------------------

# Eureka server should NOT register itself
eureka.client.register-with-eureka=false

# Eureka server should NOT fetch registry
eureka.client.fetch-registry=false

# Server hostname
eureka.instance.hostname=localhost

# Dashboard
eureka.server.enable-self-preservation=true

# Disable unnecessary logging
logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF