spring.application.name=api-gateway

server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# USER SERVICE AUTH ROUTE
# =========================

spring.cloud.gateway.server.webmvc.routes[0].id=user-service-auth
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/auth/**

# =========================
# ACTUATOR
# =========================

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always

# =========================
# JWT
# =========================

jwt.secret=MySuperSecretKeyForCinePassJwtAuthentication2026SecureKey